AddressBalanceIsLow = "address balance is low"
AddressCoinBalanceIsLow = "address coin balance is low"
AddressNotFound = "address not found"
AddressVerifyError = "address verify error"
MessageDocumentNotFound = "document not found"
MessageDocumentTagNotFound = "tag not found"
MessagePleaseSelectCommentType = "Please select a comment type"
MessagePleaseUploadPictures = "Please upload pictures"
MessageTransactionIsSuccess = "Transaction is success"
MessageTransactionNotFund = "Transaction not found"
SymbolNotFound = "symbol not found"
