AddressBalanceIsLow = "地址余额不足"
AddressCoinBalanceIsLow = "地址币种余额不足"
AddressNotFound = "地址未找见"
AddressVerifyError = "地址验证失败"
MessageDocumentNotFound = "文档不存在"
MessageDocumentTagNotFound = "文档标签不存在"
MessagePleaseSelectCommentType = "请选择问题标签"
MessagePleaseUploadPictures = "请上传图片"
SymbolNotFound = "搜索不到该代币"
